---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Verify that Zeppelin is running on port 8080
      ansible.builtin.uri:
        url: http://127.0.0.1:8080
        status_code: 200
